[package]
name = "triangle-gator"
version = "0.1.0"
edition = "2021"

[dependencies]
image={version="*", default-features=false, features=["png"]}
egui_plot = "*"
eframe = "*"
egui = "*"
# STUPID MATH SHIT
levenberg-marquardt = "0.14.0"
nalgebra = "*"
